//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ILMS")]
public interface ILMS
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILMS/Address", ReplyAction="http://tempuri.org/ILMS/AddressResponse")]
    string Address(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILMS/Address", ReplyAction="http://tempuri.org/ILMS/AddressResponse")]
    System.Threading.Tasks.Task<string> AddressAsync(string id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ILMSChannel : ILMS, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class LMSClient : System.ServiceModel.ClientBase<ILMS>, ILMS
{
    
    public LMSClient()
    {
    }
    
    public LMSClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public LMSClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LMSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LMSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Address(string id)
    {
        return base.Channel.Address(id);
    }
    
    public System.Threading.Tasks.Task<string> AddressAsync(string id)
    {
        return base.Channel.AddressAsync(id);
    }
}
